// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NguyenThanhSang505.Data;

#nullable disable

namespace NguyenThanhSang505.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20230103034110_Initial NTS505")]
    partial class InitialNTS505
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.1");

            modelBuilder.Entity("NguyenThanhSang505.CompanyNTS505", b =>
                {
                    b.Property<string>("CompanyId")
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("CompanyName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("CompanyId");

                    b.ToTable("CompanyNTS505s");
                });

            modelBuilder.Entity("NguyenThanhSang505.NTS505", b =>
                {
                    b.Property<string>("NTSId")
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<bool>("NTSGender")
                        .HasColumnType("INTEGER");

                    b.Property<string>("NTSName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("NTSId");

                    b.ToTable("NTS505s");
                });
#pragma warning restore 612, 618
        }
    }
}
